### ISSUE TITLE
Progressbar look changed in latest EAP

### ISSUE THREAD

**Issue by b1rdex** [batya239/NyanProgressBar#1]
It got some gaps and looks weird.

PhpStorm 2018.1 EAP
Build #PS-181.3494.16, built on February 7, 2018
PhpStorm EAP User
Expiration date: March 9, 2018
JRE: 1.8.0_152-release-1136-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by snowtema** [comment]
I have the same problem. 

<img width="192" alt="2018-02-22 20 56 26" src="https://user-images.githubusercontent.com/24715092/36555557-69b954d2-1813-11e8-9c05-e1cce66c084e.png">

**My environment:**
AppCode 2018.1 EAP
Mac OS High Sierra

**Comment by b1rdex** [comment]
Still not fixed for me with new version

**Comment by snowtema** [comment]
For me, it works fine!

**Comment by b1rdex** [comment]
Fixed for me in PhpStorm 2018.1 RC1 version.
