### ISSUE TITLE
The rainbow looks corrupted on Ubuntu 19.04

### ISSUE THREAD

**Issue by morozov** [batya239/NyanProgressBar#6]
The rainbow looks corrupted on Ubuntu 19.04 (Gnome Shell). I use the latest PhpStorm EAP with some other plugins. The same setup works fine with Ubuntu 16.04 (Unity).

Please see the attached screen capture.
![nyan-gnome-shell](https://user-images.githubusercontent.com/59683/64744409-a3e0cb00-d4b8-11e9-8ae8-cbf907ad9b48.gif)

**Comment by albertjt** [comment]
Happens on Ubuntu 18.04.3 LTS too

**Comment by rdewaele** [comment]
Can confirm on Arch Linux as well, with everything updated at the time of writing.
I don't know when the problem was introduced, because when I moved from MacOS to Linux in August 2019, the problem was already present (only on Linux).

**Comment by rdewaele** [comment]
I just installed the latest updates on my Arch Linux system as of 10 minutes ago and rebooted. Upon relaunching CLion I noticed this issue has now been fixed for me.
